### ISSUE TITLE
crawl

### ISSUE THREAD

**Issue by raulshum** [h4t0n/instagram-scraper#2]
i tried scraper crawl hashag, but scraper doesnt recognize crawl

**Comment by h4t0n** [comment]
You should learn how to use scrapy first. Read the documentation.

**Comment by raulshum** [comment]
i've read and i've gotten further and i'm a novice.  i now get the
following error

  File
"/home/localadmin/scrapy_instagram/scrapy_instagram/spiders/hashtag.py",
line 9, in <module>
    from scrapy_instagram.items import Post
ImportError: cannot import name Post


i am running ubuntu 16 lts with python 3.5

**Comment by raulshum** [comment]
i reinstalled and fixed the problem.  However.. i get to the point where i
asked for "name of hashtag".. after wards.. i get NameError:  name "cars'
is not defined

thanks for your time
